import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {SanityLive} from "../../../../packages/sanity/src/liveClient";
import {brandonGrotesque, cervoNeue, zillaSlab} from "./fonts";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${zillaSlab.variable} ${cervoNeue.variable} ${brandonGrotesque.variable} antialiased p-4`}
        >
        <header className={'mb-10'}>
            <h1 className={'-ml-1.5 font-logo text-[80px] font-bold uppercase leading-none tracking-wide'}>
                <>
                    <span className={'text-logo1'}>PREVIEW</span>
                    <span className={'text-logo2'}>Helnwein</span>
                </>
            </h1>
            <ul className={'flex gap-3 font-sans text-lg uppercase tracking-widest text-gray'}>
                <li className={'text-gray bg-logo2  rounded w-24 h-5 opacity-10'}/>
                <li className={'text-gray bg-logo2  rounded w-24 h-5 opacity-10'}/>
                <li className={'text-gray bg-logo2  rounded w-24 h-5 opacity-10'}/>
                <li className={'text-gray bg-logo2  rounded w-24 h-5 opacity-10'}/>
                <li className={'text-gray bg-logo2  rounded w-24 h-5 opacity-10'}/>

            </ul>
        </header>
        <div className='flex'>
            <ul className={'flex-col min-w-[260px] gap-3 md:flex hidden'}>
                <li className={'text-gray bg-logo2  rounded w-24 h-5 opacity-10'}/>
                <li className={'text-gray bg-logo2  rounded w-24 h-5 opacity-10'}/>
                <li className={'text-gray bg-logo2  rounded w-24 h-5 opacity-10'}/>
                <li className={'text-gray bg-logo2  rounded w-24 h-5 opacity-10'}/>
                <li className={'text-gray bg-logo2  rounded w-24 h-5 opacity-10'}/>
                <li className={'text-gray bg-logo2  rounded w-24 h-5 opacity-10'}/>
            </ul>
            <main>
                {children}
            </main>
        </div>
        </body>
        <SanityLive />
        </html>
    );
}
