import type {Metadata} from 'next'
import './globals.css'
import {brandonGrotesque, cervoNeue, zillaSlab} from '@/app/fonts'
import React, {FunctionComponent} from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface Props {
  children: React.ReactNode
}

const RootLayout: FunctionComponent<Props> = ({children}) => (
  <html lang="en">
    <body className={`${zillaSlab.variable} ${cervoNeue.variable} ${brandonGrotesque.variable}`}>{children}</body>
  </html>
)

export default RootLayout
